@startuml
class OutputPanel {
    + ClearOnRun : bool <<get>> <<set>> = true
    + OutputPanel()
    + PrepareForRun() : void
}
UserControl <|-- OutputPanel
OutputPanel --> "Output" JnotRichOutputBox
@enduml
