@startuml
class TestConfigMigrationStep {
    + FromVersion : string <<get>>
    + ToVersion : string <<get>>
    + Applied : bool <<get>>
    + Apply(config:RootConfig) : void
}
IConfigMigrationStep <|-- TestConfigMigrationStep
@enduml
