@startuml
class AddInRibbon {
    + AddInRibbon()
    + GetCustomUI(ribbonID:string) : string
    + Ribbon_Load(ribbonUI:Office.IRibbonUI) : void
    + OpenFileRenamer_Click(control:Office.IRibbonControl) : void
    + OpenConfig_Click(control:Office.IRibbonControl) : void
    + OpenInfo_Click(control:Office.IRibbonControl) : void
    + OpenHelp_Click(control:Office.IRibbonControl) : void
    + GetImage(control:Office.IRibbonControl) : Bitmap
}
@enduml
