@startuml
class InfoMetadata <<static>> {
    + {static} Version : string <<get>>
    + {static} BuildDate : string <<get>>
    + {static} ConfigPath : string <<get>>
    + {static} LogFolder : string <<get>>
    + {static} DotNetVersion : string <<get>>
    + {static} OSVersion : string <<get>>
    + {static} ProcessBitness : string <<get>>
    + {static} MemoryUsage : string <<get>>
}
@enduml
