@startuml
!include .\\Excel.AddIn\ThisAddIn.puml
!include .\\Excel.AddIn\ThisAddIn.Designer.puml
!include .\\Excel.Interop\ExcelReader.puml
!include .\\Excel.Interop\ExcelWorkbookDataSource.puml
!include .\\Excel.Interop\HeaderBlock.puml
!include .\\Excel.Interop\IWorkbookDataSource.puml
!include .\\Excel.Interop\ParameterBlock.puml
!include .\\Excel.Interop\ParamSitePair.puml
!include .\\Excel.Interop\PivotData.puml
!include .\\Excel.Interop\PivotParser.puml
!include .\\FileRenamer\Class1.puml
!include .\\Shared.Config\Class1.puml
!include .\\Shared.Config.Tests\UnitTest1.puml
!include .\\Shared.FileSystem\InputFolderScanner.puml
!include .\\Shared.FileSystem\OutputFolderWriter.puml
!include .\\Shared.FileSystem\SafeRenameService.puml
!include .\\Shared.Info\InfoMetadata.puml
!include .\\Shared.Info\InfoPaneProvider.puml
!include .\\Shared.Logging\Logger.puml
!include .\\Shared.UI\Class1.puml
!include .\\Shared.UI\ITaskPaneContentProvider.puml
!include .\\Shared.UI\JnotTaskPane.puml
!include .\\Shared.UI.Controls\CardSection.puml
!include .\\Shared.UI.Controls\CollapsibleCardSection.puml
!include .\\Shared.UI.Controls\CollapsibleSection.puml
!include .\\Shared.UI.Controls\ExpandableCard.puml
!include .\\Shared.UI.Controls\ExpandableCard.Designer.puml
!include .\\Shared.UI.Controls\ExpandableSection.puml
!include .\\Shared.UI.Controls\ExpandableSection.Designer.puml
!include .\\Shared.UI.Controls\JnotLogLevel.puml
!include .\\Shared.UI.Controls\JnotRichOutputBox .puml
!include .\\Shared.UI.Controls\UserControl1.puml
!include .\\Shared.UI.Controls\UserControl1.Designer.puml
!include .\\ThrowAway.Demo\Class1.puml
!include .\\Excel.AddIn\Properties\AssemblyInfo.puml
!include .\\Excel.AddIn\Properties\Resources.Designer.puml
!include .\\Excel.AddIn\Properties\Settings.Designer.puml
!include .\\Excel.Interop\Properties\AssemblyInfo.puml
!include .\\FileRenamer\Business\Pattern.puml
!include .\\FileRenamer\Business\PatternEngine.puml
!include .\\FileRenamer\Business\RenameEngine.puml
!include .\\FileRenamer\Config\ConfigPaneProvider.puml
!include .\\FileRenamer\Config\FileRenamerConfigAdapter.puml
!include .\\FileRenamer\Config\IFileRenamerConfigAdapter.puml
!include .\\FileRenamer\UI\FileRenamerPaneProvider.puml
!include .\\Shared.Config\Defaults\ConfigDefaults.puml
!include .\\Shared.Config\IO\ConfigFileLocator.puml
!include .\\Shared.Config\IO\ConfigLoader.puml
!include .\\Shared.Config\IO\ConfigWriter.puml
!include .\\Shared.Config\Migration\ConfigMigrationEngine.puml
!include .\\Shared.Config\Migration\IConfigMigrationStep.puml
!include .\\Shared.Config\Models\FileRenamerConfig.puml
!include .\\Shared.Config\Models\RootConfig.puml
!include .\\Shared.Config\Services\ConfigService.puml
!include .\\Shared.Config\Services\IConfigService.puml
!include .\\Shared.Config\Validation\ConfigValidationResult.puml
!include .\\Shared.Config\Validation\ConfigValidator.puml
!include .\\Shared.UI.Controls\Panels\OutputPanel.puml
@enduml
