@startuml
class FileRenamerConfigAdapter {
    + FileRenamerConfigAdapter(configService:IConfigService)
    + GetConfig() : FileRenamerConfig
}
IFileRenamerConfigAdapter <|-- FileRenamerConfigAdapter
@enduml
